src/scripts/slate/currency.js, src/scripts/slate/utils.js
Fixes #113 
Following the lead of PR https://github.com/Shopify/slate/pull/78, Lodash's `_.defaultTo` function was added to `slate.utils`
Now the `formatWithDelimiters` function inside `slate.Currency` can correctly apply a default value of `2` if the `precision` argument equals `0`—as well as any other place where a default variable needs to be set.
https://github.com/lodash/lodash/blob/master/defaultTo.js
```js
slate.utils.defaultTo(1, 10)
// => 1
slate.utils.defaultTo(0, 10)
// => 0
slate.utils.defaultTo(undefined, 10)
// => 10
```
=> Add defaultTo function

src/sections/featured-product.liquid, src/sections/product.liquid
Use `product.position` instead of `forloop.index` as it is more accurate in what the JS is trying to accomplish in variant selection.  Now the JS isn't tied to the product options being listed in the same order as the admin.
Documentation for public site PR has already been made here: https://github.com/Shopify/documentation/pull/9525
Also, I've put in the stronger check for default variant that we've implemented in our other themes.
=> Add product position

src/scripts/sections/product.js, src/sections/featured-product.liquid, src/sections/product.liquid
Fixes https://github.com/Shopify/slate/issues/96
* Always render markup for compare at price, so JS can update it.
* On featured product page, use `current_variant` information so the initial prices displayed reflect the option selectors.
New stuff:
The changes in `product.js` have to do with how we are handling compare_at information when the variant is on sale.  We are always leaving the "compare_at" text on screen for screenreaders, even when we were hiding the sale price. Now it hides that text if the variant isn't on sale.
I also update the strikethrough price when the variant isn't on sale.  It was already being hidden with the `hide` class, but it just felt odd to leave a strikethrough price in the markup if we had no intention of using it.
/cc @Shopify/themes-fed 
For …
=> Compare at price logic

README.md
Fix the readme license link, it was 404'ing previously.
@NathanPJF
=> Fix broken license link in readme

docs/_includes/sidebar.html, docs/theme-scaffold/index.md
* Provide more information about how Sass is handled by both Slate and Shopify
* Been getting questions about what version of Sass Shopify uses or why Sass is failing to compile.
* Give more helpful links about translation keys and info on how to use them.
* Flesh out the JavaScript section a bit more.
=> Docs theme scaffolding sass, js, and locales

docs/js-examples/index.md, src/scripts/slate/sections.js
* Add a `onReorder` method to registered sections.
* Document this new method.
Public docs for `shopify:section:reorder`: https://help.shopify.com/themes/development/theme-editor/sections#theme-editor-javascript-api
=> add to docs and section-js

docs/css-examples/index.md
Possible typo in documentation. Couldn't follow example until I changed to ```@include media-query(...)```
```@mixin media-query($media-query) { ... }``` in src/styles/tools/mixins.scss
Cannot find an existing open issue for this.
=> Change media mixin to media-query

docs/commands/index.md
Adds `slate test` command documentation to `/docs`. Similar PR for Slate CLI can be found [here](https://github.com/Shopify/slate-cli/pull/120) and the `slate test` command PR can be found [here](https://github.com/Shopify/slate-tools/pull/55).
=> Add test command documentation

docs/theme/index.md
Just noticed an extra word while reading the docs. Removed it!
=> Remove Extra 'two' in theme docs

src/sections/collection-list.liquid, src/sections/featured-product.liquid, src/sections/product.liquid
Fixes #89.
Reference in documentation for proper empty drop usage: https://help.shopify.com/themes/liquid/basics/types#emptydrop
=> Modify checks for empty drops

src/locales/de.json, src/locales/en.default.json, src/locales/es.json, src/locales/fr.json, src/locales/pt-BR.json, src/locales/pt-PT.json, src/sections/footer.liquid
Fixes #86. The output for the payment icons in the footer now look like:
=> Update for accessible payment icons

src/config/settings_schema.json
Update the `theme_info` to remove Theme Support as the support email.  That group is not responsible for maintaining the code base.  
Switched it for `theme_support_url` so theme devs still know that you can separate the ideas of documentations and support.
Changed the theme version number to represent what we do for internally developed themes where the `theme_version` matches the `package.json` version. 
=> remove theme-support email, not theirs to support

src/sections/featured-product.liquid, src/sections/product.liquid, src/templates/cart.liquid
There is a new product drop used for detecting whether a product only has the default variant: `product.has_only_default_variant`.  (Public docs are being updated and in review)
This PR removes the complicated and fragile check for "default product option" values.  This detection is now moved to Shopify's side.
I removed `{% if option.name == 'default' %}class="label-hidden"{% endif %}` on the `<label>` elements.  Reason: If the merchant has left the product option as "Default" in the admin, then we'll display it here.  The new drop will take care of the single default variant check earlier in the markup.
=> use product drop for detecting default variant

docs/index.md
Node version statement was removed in an earlier commit.  This adds a statement about what version is supported.
=> Node version statement

.gitignore, .gitignore-sample, docs/index.md, scripts/build
Partially address https://github.com/Shopify/slate/issues/126
Creating a sample gitignore tailored for a new Slate project.  The `.gitignore-sample` file is now part of `slate-src.zip` which is used by the `theme.js` command in `slate-cli`.
=> add a sample gitignore

src/scripts/slate/a11y.js
Fix #186.
Updated the `eventName` variable with the proper object property.
=> trapFocus() - Replace eventNameSpace with namespace

src/styles/global/normalize.scss
Fixes https://github.com/Shopify/slate/issues/121
=> Update normalize scss to v6

src/sections/header.liquid, src/styles/modules/site-header.scss
Fixes https://github.com/Shopify/slate/issues/172
=> Update settings for header section

packages/slate-theme/src/styles/theme.scss
When developers add certain UTF-8 characters to their `theme.scss` file such as a trademark symbol `©`, an accent such as `ë`, or a proud deer `🦌`, the stylesheet will not load properly on storefront.
This was first noted in https://github.com/Shopify/slate/issues/204 and again in https://github.com/Shopify/slate/issues/241.
This PR adds the fix to the main stylesheet.  Hopefully this will prevent future devs from running into this issue.   🙏🔮😄
The broken stylesheet behaviour is only seen outside the theme editor.  Within the theme editor, the stylesheet loads fine because the asset goes through a separate build process than storefront.
=> add charset to stylesheet

packages/slate-tools/src/tasks/build-assets.js, packages/slate-tools/src/tasks/watchers.js
Fixes https://github.com/Shopify/slate/issues/227
Ignores watching `.DS_store` and any other dot files in the `dist/` directory.
=> Ignore watching dot files in dist/ directory

packages/slate-theme/src/scripts/sections/product.js, packages/slate-theme/src/sections/featured-collection.liquid, packages/slate-theme/src/sections/featured-product.liquid, packages/slate-theme/src/sections/product.liquid, packages/slate-theme/src/templates/cart.liquid, packages/slate-theme/src/templates/collection.liquid, packages/slate-theme/src/templates/search.liquid
Fixes https://github.com/Shopify/slate/issues/99
- Fixes `feature-product.liquid` section by removing placeholder image if no image is set. Also matches `product.liquid` section behaviour by setting the featured image as either the current variant's featured image or the product featured image
- Fixes `product.liquid` by checking if featured image is not black
- Fixes `product.js` by only performing image functions if an image is present on the page. There was some code that was rearranged to make this check easy.
=> Fix behaviour and errors when no product image

scripts/build.js
[`slate-src.zip v0.12.0`](https://sdks.shopifycdn.com/slate/0.12.0/slate-src.zip) has its files in the `packages/slate-theme` directory. This patch fixes the zip to be the same structure as <v0.12.0.
cc @chrisberthe @NathanPJF
=> Fix the output of slate-src.zip

packages/slate-theme/src/scripts/sections/product.js
- scripts/sections/product.js, this.productSingleObject needs to be initialized before using it in options object.
- line 59, scripts/sections/product.js, this.$featured_image is not a defined variable (it's a typo), needs to be replaced with this.$featuredImage
Some basic fixes in scripts/sections/product.js
=> Fix typo and variable declaration order in product.js

packages/slate-theme/src/locales/da.json, packages/slate-theme/src/locales/de.json, packages/slate-theme/src/locales/en.default.json, packages/slate-theme/src/locales/es.json, packages/slate-theme/src/locales/fr.json, packages/slate-theme/src/locales/nl.json, packages/slate-theme/src/locales/pt-BR.json, packages/slate-theme/src/locales/pt-PT.json, packages/slate-theme/src/templates/customers/order.liquid
A recent Liquid update to `fulfillment.tracking_url` had it stop returning a Google search URL if a tracking number was provided, but the tracking URL or company was unknown. Example: `http://www.google.com/search?q=78714763445730`. 
If the tracking URL is unknown, `{{ fulfillment.tracking_url }}` now returns `nil`. 
This PR is made to only output the tracking URL if it is known.  
To help customers who have no URL, this PR displays more information about the tracking company and tracking number if it is known.
Note: The tracking company always has a value in Shopify.  If none is provided, it will say "Other".
=> Tracking information for order page

docs/js-examples/index.md, packages/slate-theme/src/scripts/slate/rte.js, packages/slate-theme/src/scripts/theme.js
Instead of hard-coding selector & class strings directly in the wrapper methods, we allow parameters to be passed in, which improves the scalability and reusability of these methods when creating a new theme.
=> Add parameters to RTE wrapper methods

packages/slate-theme/src/locales/da.json, packages/slate-theme/src/locales/de.json, packages/slate-theme/src/locales/en.default.json, packages/slate-theme/src/locales/es.json, packages/slate-theme/src/locales/fr.json, packages/slate-theme/src/locales/nl.json, packages/slate-theme/src/locales/pt-BR.json, packages/slate-theme/src/locales/pt-PT.json, packages/slate-theme/src/templates/gift_card.liquid
Always display the gift card's initial value, which currently never shows up. The only value that appears is the card's balance, and that only appears when when it's not equal to the card's initial value. This should fix a [comment](https://github.com/Shopify/slate/issues/279#issuecomment-328591550) posted on issue #279. (fix #279)
=> Display the gift card's initial value

packages/slate-theme/src/scripts/slate/rte.js
Fixes #293
To prevent this silent failure/unintended behaviour, I've added a `typeof` check so only strings may be applied. 
=> Rte helpers fallback class

docs/_includes/head.html
Currently all the slate documentation has the meta tag "noindex" applied to it. This prevents search engines from index and showing the page in search results.
We can see that Google specifies [here](https://developers.google.com/search/reference/robots_meta_tag) what noindex means ("Do not show this page in search results and do not show a "Cached" link in search results.")
Since the default behavior is to index a page if it doesn't specify the meta robots tag we can safely just remove it
=> Ensure that slate documentation is indexed by search engines

packages/slate-tools/src/tasks/includes/dev-script.js
Change the dev-scripts click event to bind on just the minimize button on the preview bar instead of on the entire document.
=> Change dev script click event target from document to minimize button

packages/slate-tools/src/tasks/deploy-utils.js
Fix #249. This PR fixes the `open:zip` Gulp task on Windows by changing the path to the Upload folder to be platform agnostic.
Since Windows and Unix-like operating systems use different path separators — backslashes in Windows (`\`) vs "common" slashes in Unix-like OSes (`/`) — the `open:zip` task would fail on Windows because of the Unix style slashes (`/`) used in the path to the `upload` folder.
=> Fix Upload folder path in 'open:zip' gulp task

packages/slate-cli/src/commands/migrate.js, packages/slate-cli/src/utils.js
Beautify the settings files (`settings_*.json`) upon migration (fix #224).
The settings files are pretty printed (indented with 2 spaces).
=> Beautify settings files on migration

packages/slate-theme/src/sections/header.liquid
Fixes #237.
Update nested nav liquid. As discussed IRL with @t-kelly, we're also stripping down the classes and the arrow down icon to make it as barebone as possible.
**This need to be merged only when the new liquid is rolled out 100%**
=> Update main navigation liquid to support 3 level

packages/slate-config/__tests__/fixtures/schema.js, packages/slate-config/__tests__/validate.test.js, packages/slate-config/validate.js
Add support for type `array` in the `slate-config` package. Also added an `extractType` function so that we can easily extend the types supported by `slate-config`
Add specific check for type `array` in `slate-config` schema validation.
=> Add support for type array in slate config

README.md
Update the README.md documentation to include environment details for `yarn start` in the **Start Developing** section.  The language was pulled and adapted from the [slate-env package's README](https://github.com/Shopify/slate/tree/1.x/packages/slate-env).
https://github.com/Shopify/slate/issues/399
=> Add docs on using yarn start with env flag

packages/slate-cssvar-loader/__tests__/fixtures/css-variables.liquid, packages/slate-cssvar-loader/__tests__/fixtures/expected-disabled.js, packages/slate-cssvar-loader/__tests__/fixtures/expected.js, packages/slate-cssvar-loader/__tests__/fixtures/test.css, packages/slate-cssvar-loader/index.js
Fix an issue in the `slate-cssvar-loader` so that it grabs everything after the `:` and not just the liquid variable. For example, currently 
```liquid
--letter_spacing: {{ settings.letter_spacing }}px;
``` 
would be replaced with 
```css
letter-spacing: {{ settings.letter_spacing }};
```
With this change, the `px` will be carried over so that the resulting CSS is 
```css
letter-spacing: {{ settings.letter_spacing }}px;
```
=> Grab the entire cssvar value when running the slate-cssvar-loader

packages/slate-config/__tests__/index.test.js, packages/slate-config/index.js, packages/slate-env/README.md, packages/slate-env/index.js, packages/slate-env/slate-env.config.js
Fixes #398. Generates the following `.env` file:
```bash
SLATE_STORE=
SLATE_PASSWORD=
SLATE_THEME_ID=
SLATE_IGNORE_FILES=
```
=> Add helpful comments to generated `.env` file

packages/slate-tools/cli/commands/build.js
=> marks webpack compilation script error with process.exit(1)

README.md
Created clearer documentation on using settings_schema properties in scss with slate 1.x
Associated [GitHub Issue 1](https://github.com/Shopify/slate/issues/421)
Associated [GitHub Issue 2](https://github.com/Shopify/slate/issues/423)
=> Clearer SCSS Documentation

packages/slate-theme/src/sections/footer.liquid
Add google_pay as available payment type. This will need to be merged after https://github.com/Shopify/shopify/pull/148070.
=> Add google_pay as available payment type

packages/create-slate-theme/index.js
Previously, the JS file that checked what version of Node was running was using JS language features available only in Node 6+. This caused a runtime error when the file was run in Node <6.
Switch out Node 6+ features for equivalent legacy alternatives so the Node version warning can be displayed. Disable ESLint so that Prettier does not apply ES6 formatting.
=> Fix Node version check and error

packages/create-slate-theme/__mocks__/hosted-git-info.js, packages/create-slate-theme/__tests__/create-slate-theme.test.js, packages/create-slate-theme/__tests__/index.test.js, packages/create-slate-theme/create-slate-theme.config.js, packages/create-slate-theme/create-slate-theme.js, packages/create-slate-theme/index.js
Fixes https://github.com/Shopify/slate/issues/444
Switch to use `https` url when cloning Git repos. This will allow public repos (https://github.com/Shopify/starter-theme) to be cloned by users who do not have a Github account.
Also added a `--ssh` flag which will continue to allow developers to use SSH, which is more convenient for private repos.
=> Default to https when cloning new Slate theme

packages/slate-sync/__tests__/prompt-if-settings-data.test.js, packages/slate-sync/index.js, packages/slate-sync/package.json, packages/slate-sync/prompt-skip-settings-data.js, packages/slate-sync/slate-sync.config.js, packages/slate-tools/cli/commands/start.js, yarn.lock
=> Prompt user if uploading settings_data.json

packages/slate-tools/README.md, packages/slate-tools/cli/commands/format.js, packages/slate-tools/cli/commands/lint.js, packages/slate-tools/cli/index.js, packages/slate-tools/package.json, packages/slate-tools/slate-tools.config.js, packages/slate-tools/tools/eslint/__tests__/index.test.js, packages/slate-tools/tools/eslint/index.js, packages/slate-tools/tools/prettier/__tests__/index.test.js, packages/slate-tools/tools/prettier/index.js, packages/slate-tools/tools/stylelint/__tests__/index.test.js, packages/slate-tools/tools/stylelint/index.js, packages/slate-tools/tools/theme-lint/__tests__/index.test.js, packages/slate-tools/tools/theme-lint/index.js, yarn.lock
Adds `lint` and `format` commands to `@shopify/slate-tools`
`lint` command does the following:
- Lints JS files using ESLint and `.eslintrc` 
- Lints CSS, SCSS, and SASS using Stylelint and `.stylelintrc`
- Lints locales using [`@shopify/theme-lint`](https://github.com/Shopify/theme-lint)
- Accepts `--scripts`, `--styles`, and `--locales` flags to selectively lint file types
'format' command does the following:
- Fixes JS files using ESLint `--fix` and `.eslintrc`
- Fixes CSS,SCSS, and SASS using Stylelint `--fix` and `.stylelint.rc`
- Fixes JSON files using Prettier
- Accepts `--scripts`, `--styles`, and `--json` flags to selectively fix file types
Related: https://github.com/Shopify/slate/projects/1#card-6750115, #257
=> Add lint and format command

packages/slate-sync/__tests__/skip-settings-data.test.js, packages/slate-sync/continue-if-published.js, packages/slate-sync/index.js, packages/slate-sync/package.json, packages/slate-sync/skip-settings-data.js, packages/slate-tools/cli/commands/start.js
Fixes https://github.com/Shopify/slate/issues/427
Prompts are helpful for real people who need a little help catching a potential mistake, but they're not as helpful for computers. This PR adds a `--skipPrompts` flag which can be added to `slate-tools start` or `slate-tools deploy` to ignore prompts and continue with default behaviour.
Also removes the prompt in `slate-tools deploy` which asks if you're sure you want to deploy, regardless of the configuration. This prompt was overkill and not needed.
=> Add --skipPrompts flag

packages/slate-sync/index.js, packages/slate-tools/README.md, packages/slate-tools/cli/commands/deploy.js
Fixes #463 
Changes the default behaviour of the Slate Tools `deploy` command so that, by default, it only updates and adds new files to a specified theme. This behaviour DOES NOT delete files which are not in your Slate project.
The previous behaviour of deploy, one which replaces all files on your store's theme with that of your Slate project, can be enabled via the `--replace` flag. This behaviour DOES result in the deletion of files which are not in your Slate project.
=> Add --replace flag to the deploy command

packages/slate-config/index.js
Causing some default values to be overrided by a value of `undefined`.
=> Incorrect type checking when building config objects

packages/concat-style-loader/concat.js, packages/concat-style-loader/index.js, packages/concat-style-loader/package.json, packages/concat-style-loader/test/concat.test.js, packages/concat-style-loader/test/fixtures/another.css, packages/concat-style-loader/test/fixtures/concatenated.css, packages/concat-style-loader/test/fixtures/more.css, packages/concat-style-loader/test/fixtures/other.css, packages/concat-style-loader/test/fixtures/style.css, packages/concat-style-loader/test/helpers/app.js, packages/concat-style-loader/test/helpers/compiler.js, packages/slate-tools/package.json, packages/slate-tools/tools/webpack/config/core.js, packages/slate-tools/tools/webpack/config/dev.js, packages/slate-tools/tools/webpack/config/prod.js, packages/slate-tools/tools/webpack/html-webpack-include-chunks.js, packages/slate-tools/tools/webpack/static-files-glob.js, packages/slate-tools/tools/webpack/style-tags.html, yarn.lock
Fixes #258 
Adds legacy support to `.scss.liquid` and `.css.liquid` files. Replaces any CSS `@import` declarations with the inlined file, similar to [`gulp-cssimport`](https://github.com/unlight/gulp-cssimport) used by Slate v0.
Generates a `theme.scss.liquid` file which will be compiled by Shopify servers.
=> Add concat-style-loader to handle Liquid Style files

packages/slate-cssvar-loader/slate-cssvar-loader.config.js
Fix default configs for `cssVarLoaderLiquidPath ` in the `slate-cssvar-loader` package. The path value expects a path instead of a string. 
=> Fix default cssVarLoaderLiquidPath for the slate-cssvar-loader package

packages/concat-style-loader/concat.js, packages/concat-style-loader/test/concat.test.js
Helps avoid https://github.com/Shopify/slate/issues/502
=> Ignore `@import` statements which are not followed by `url(..)`

packages/slate-cssvar-loader/__tests__/fixtures/css-variables.liquid, packages/slate-cssvar-loader/__tests__/fixtures/expected-disabled.js, packages/slate-cssvar-loader/__tests__/fixtures/expected.js, packages/slate-cssvar-loader/__tests__/fixtures/test.css, packages/slate-cssvar-loader/index.js
Escapes double quotes from liquid variables during cssvar replacement.
Fixes #511
=> [slate-cssvar-loader] Escape double quotes from liquid variable

packages/slate-tools/cli/commands/build.js
The webpackConfig object passed to Slate Analytics had a circular reference within in, which does not play well with `JSON.stringify`. We don't really need to be collecting the config for now so I just removed it.
=> Remove circular reference in Slate Analytics event

packages/html-webpack-liquid-asset-tags-plugin/index.js
Html-webpack-liquid-asset-tags-plugin was using `Tapable.plugin()` syntax, which is deprecated in Webpack 4. Swap to use `Tapable.hooks` syntax instead.
=> Update liquid-asset-plugin to use tapable.hooks

packages/slate-cssvar-loader/slate-cssvar-loader.config.js
We currently require users to create a [`snippets/css-variables.liquid`](https://github.com/Shopify/starter-theme/blob/91a62bad7da4666b561a2e053551e35c36ff7cd6/src/snippets/css-variables.liquid) file in order to use Slate out of the box. This file is used to declare CSS variables which are linked to Liquid variables.
This snippet is completely unnecessary, and the creation of a snippet should be left to the discretion of the theme developer. Let's default to using `layout/theme.liquid` as the file in which we search for CSS variable declarations.
To reverse this behaviour, developers can specify a snippet by declaring the following in their `slate.config.js`:
```
module.exports = {
slateCssVarLoader: {
cssVarLoaderLiquidPath: [ __dirname + 'src/snippets/css-variables.liquid'];
}
};
```
=> Change the the default CSS var declaration file to theme.liquid

packages/slate-tools/slate-tools.config.js, packages/slate-tools/tools/webpack/config/core.js, packages/slate-tools/tools/webpack/static-files-glob.js
=> Breaking: assets/vendors to assets/static

packages/slate-analytics/prompt.js
Now that Slate v1 is in master branch, the URL presented when we ask for consent to collect analytics data is out of date. This updates that URL to reference the docs in the Slate wiki.
=> Update the URL for analytics docs

packages/slate-tools/src/tasks/includes/messages.js, packages/slate-tools/src/tasks/watchers.js
Fixes https://github.com/Shopify/slate/issues/243
Its not possible to see error details if the error thrown by the Themekit child process is not a string. This makes sure that we log all watch errors in the deploy log, including those which are not strings.
=> Make sure we log errors on watch command

packages/slate-theme/src/scripts/slate/currency.js
Fixes https://github.com/Shopify/slate/issues/543
=> Fix currency JS formatting names to match Shopify core

packages/slate-analytics/__tests__/index.test.js, packages/slate-analytics/index.js, packages/slate-analytics/package.json, packages/slate-analytics/prompt.js, packages/slate-analytics/utils.js, packages/slate-env/__tests__/index.test.js, packages/slate-env/index.js, packages/slate-env/slate-env.config.js
Fixes https://github.com/Shopify/slate/issues/585
Related https://github.com/Shopify/slate/issues/552
Adds a new environment variable `SLATE_USER_EMAIL` to `@shopify/slate-env`. When setting this value to a valid email, `@shopify/slate-analytics` will use it to consent to data collection instead of prompting the user.
cc @markdavies
=> Add SLATE_USER_EMAIL env variable for slate-analytics

packages/slate-tools/tools/eslint/index.js
Fixes https://github.com/Shopify/slate/issues/596.  Adds the `src/assets/static` folder to the list of ignore patterns as part of Slate Tools.
There is currently another PR that does the same thing on the theme level: https://github.com/Shopify/starter-theme/pull/83.
=> Add static folder to list of ignore patterns

packages/slate-cssvar-loader/index.js
Modified slate-cssvar-loader not to prevent deploying when no matching liquid variable is found for a CSS variable.
I'm attempting to solve the issue I reported that prevents the use of regular CSS variables without corresponding Liquid variables.
https://github.com/Shopify/slate/issues/524
I do not believe any documentation for local SASS compilation needs to be updated to reflect this change. This documentation is the most relevant:
https://github.com/Shopify/slate/wiki/Local-SASS-compilation
=> Modified slate-cssvar-loader to allow CSS variables without Liquid variables

packages/slate-tools/tools/webpack/config/core.js
Last released introduced a bug which would cause your build to fail if your project didn't have a folder that has its contents copied to dist, e.g if you were missing the `src/assets/fonts` directory. This removes the requirement to have these folders.
=> Fix build break when missing fonts directory

packages/slate-tools/tools/webpack/config/core.js
This PR extends webpack configuration to support .otf fonts.
I need that for my project but also mentioned here: https://github.com/Shopify/slate/issues/418#issuecomment-392568520
=> Add .otf font support in webpack config

packages/slate-tools/tools/webpack/script-tags.html
Fixes https://github.com/Shopify/slate/issues/715
Shared bundles (e.g. a bundle named template.index@template.product.js) were not having all pages added to the liquid condition that decided whether the page should be rendered with a `<script>` or `<link>` tag. Instead of generating:
```
{%- if template.name == 'index' or template.name == 'product' -%}
```
it would only generate
```
{%- if template.name == 'product' -%}
```
=> Fix conditions for generating script tags

packages/slate-analytics/index.js, packages/slate-analytics/prompt.js, packages/slate-tools/cli/commands/start.js
Checks if `process.env.NODE_ENV === 'test'` before clearing the console. It's annoying to see half your test results disappear as you test!
=> Stop clearing console when testing

packages/slate-tools/tools/webpack/config/parts/__tests__/sass.prod.test.js, packages/slate-tools/tools/webpack/config/parts/sass.prod.js, packages/slate-tools/tools/webpack/config/prod.js
Followup to https://github.com/Shopify/slate/pull/737
- Adds test for 'webpack.cssnano.settings' which makes sure the config is passed to cssnano
- Isolates the sass rule for webpack in its own file to make it easier to test
=> Add tests for cssnano config item

packages/slate-tools/tools/webpack/config/core.js, packages/slate-tools/tools/webpack/config/dev.js, packages/slate-tools/tools/webpack/config/parts/babel.js, packages/slate-tools/tools/webpack/config/parts/sass.prod.js, packages/slate-tools/tools/webpack/config/prod.js, packages/slate-tools/tools/webpack/config/utilities/__tests__/common-excludes.test.js, packages/slate-tools/tools/webpack/config/utilities/common-excludes.js
Followup to #738 
- Move common-excludes.js to tools/webpack/utilities folder
- Update require path for common-excludes.js
- Add test to check if 'webpack.commonExcludes' values are being passed
=> Add test for 'webpack.commonExcludes' config

packages/slate-tools/tools/webpack/config/__tests__/dev.test.js, packages/slate-tools/tools/webpack/config/__tests__/prod.test.js, packages/slate-tools/tools/webpack/config/dev.js, packages/slate-tools/tools/webpack/config/prod.js
Follow-up to #739 
Adds tests that make sure 'webpack.config.extend.prod' and 'webpack.config.extend.dev' are passed to webpack-merge.
=> Add tests for 'webpack.config.extend.prod' and 'webpack.config.extend.dev'

packages/slate-tools/tools/webpack/config/__tests__/dev.test.js, packages/slate-tools/tools/webpack/config/__tests__/prod.test.js, packages/slate-tools/tools/webpack/config/dev.js, packages/slate-tools/tools/webpack/config/parts/__tests__/entry.test.js, packages/slate-tools/tools/webpack/config/parts/core.js, packages/slate-tools/tools/webpack/config/parts/entry.js, packages/slate-tools/tools/webpack/config/prod.js, packages/slate-tools/tools/webpack/config/utilities/get-layout-entrypoints.js, packages/slate-tools/tools/webpack/config/utilities/get-template-entrypoints.js
Follow-up to #740 
- Moves `webpack/config/core.js` to `webpack/config/parts/core.js`
- Creates a new `parts/entry.js`
- Isolates logic for determining Template and Layout entrypoints into their own files, get-template-entrypoints.js and get-layout-entrypoints.js
- Adds test which checks if 'webpack.entrypoints' object is merged into the output of `parts/entry.js`
=> Add test for 'webpack.entrypoints' config

packages/slate-tools/slate-tools.schema.js, packages/slate-tools/tools/stylelint/__tests__/index.test.js, packages/slate-tools/tools/stylelint/index.js
Follow-up to #743 
BREAKING: Your project will now require a .stylelintignore file to ignore linting dist/ and node_modules/ directories
- Pass 'stylelint.config' to --config flag
- Pass 'stylelint.ignorePath' to --ignore-path
- Add tests for all config items
=> Add config tests for stylelint

packages/slate-tools/slate-tools.schema.js, packages/slate-tools/tools/prettier/__tests__/index.test.js, packages/slate-tools/tools/prettier/index.js
- Pass 'prettier.config' to --config flag
- Pass 'prettier.ignorePath' to --ignore-path
- Add tests for all config items
=> Add tests to prettier config items

packages/slate-tools/slate-tools.schema.js, packages/slate-tools/tools/eslint/__tests__/index.test.js, packages/slate-tools/tools/eslint/index.js
BREAKING: Themes will need a .eslintignore file to ignore 'dist', 'node_modules', 'src/assets/static' files
- Pass 'eslint.config' to the --config flag
- Pass 'eslint.ignorePath' to --ignore-path
- Add tests for all config items
=> Add tests to Eslint config items

packages/slate-config/__tests__/index.test.js, packages/slate-config/index.js
With the config updates it is possible to set a config value as a function. This function had access to the SlateConfig instance, allowing you to fetch other config values:
```js
// slate-tools.schema.js
module.exports = {
'webpack.postcss.plugins': (config) => [
autoprefixer,
...(process.env.NODE_ENV === 'production'
? [cssnano(config.get('webpack.cssnano.settings'))]
: []),
]
};
```
However, one thing that was not possible to do was extend the default value of a config item. If the above config was the default value declared, and you wanted to add another PostCSS plugin while keeping the defaults, you would need to redeclare the default values plus add your own:
```js
// slate.config.js
const autoprefixer = require('autoprefixer');
const cssnano = require('cssnano');
const …
```
=> Pass computed default value to slate.config.js functions

packages/slate-tools/tools/webpack/config/utilities/get-template-entrypoints.js, packages/slate-tools/tools/webpack/script-tags.html, packages/slate-tools/tools/webpack/style-tags.html
Fixes https://github.com/Shopify/slate/issues/707
Now when you have: 
- `template/page.liquid`
- `templates/page.alternate.liquid`
- `scripts/templates/page.js`
- `scripts/templates/page.alternate.js`
The following bundles are generated:
- `template.page.js`
- `template.page.alternate.js`
And the following conditions generated in `snippets/style-tags.liquid`:
```
{%- if template == 'product.alternate' -%}
<script type="text/javascript" src="{{ 'template.product.alternate.js' | asset_url }}" defer="defer"></script>
{%- else -%}
<link rel="prefetch" href="{{ 'template.product.alternate.js' | asset_url }}" as="script">
{%- endif -%} 
{%- if template == 'product' -%}
<script type="text/javascript" src="{{ 'template.product.js' | asset_url }}" defer="defer"></script>
{%- else -%}
<link …
```
=> Fix alternative template bundles

packages/slate-tools/cli/prompts/disable-external-testing.js, packages/slate-tools/cli/prompts/tests/disable-external-testing.test.js, packages/slate-tools/slate-tools.schema.js
Fix #757 
Adds `'network.externalTesting'` config which will toggle using localhost or your local IP for referencing development assets. If you use localhost, you will probably encounter problems with SSL authentication when visiting your dev shop from an external device.
=> Add configuration to disable external testing using local IP

packages/slate-tools/tools/webpack/config/parts/core.js
Fixes #708 
Ignores `.DS_Store` files when copying SVGs to the snippets folder
=> Ignore copying .DS_Store on build

.gitignore, package.json, packages/slate-tools/package.json, packages/slate-tools/tools/asset-server/app.js, yarn.lock
Fixes #676 
- webpack-dev-middleware: v1.10.2 => v3.4.0
- write-file-webpack-plugin: v4.2.0 => v4.4.9
=> Update dependencies to remove Tapable.plugin warning

packages/slate-tools/package.json, packages/slate-tools/tools/webpack/config/dev.js, packages/slate-tools/tools/webpack/config/parts/css.js, packages/slate-tools/tools/webpack/config/parts/sass.js, packages/slate-tools/tools/webpack/config/prod.js, yarn.lock
- Fixes #677 : Adds a rule to the Webpack config to handle importing `.css` files directly from `.js` files. Previously, it was only possible to import `.css` files from inside `.scss` files.
- Fixes #785 : Removes `webpack.commonExcludes` from rule `excludes`. No need to ignore the assets or node_module directories with these rules.
- Fixes #797 : Migrates style rules to use `css-mini-extract-plugin` instead of `extract-text-webpack-plugin`
=> Add rule to webpack config to handle .css files

packages/slate-tools/tools/webpack/config/utilities/get-template-entrypoints.js, packages/slate-tools/tools/webpack/script-tags.html, packages/slate-tools/tools/webpack/style-tags.html
After allowing alternate template bundles in beta.8, the liquid logic included in `script-tags.liquid` snippet to check which bundles to load and which bundles to prefetch, was updated to use `template` from `template.name`. This creates a problem for any template that's included in the `customers/` directory because the value that's used to create the template name in the liquid logic is taken from the chunk inside the webpack plugin. This is a problem because bundles/entry points inside the `customers/` directory are flattened down to the same level as the other files, which produces files like this:
```
template.login.js
template.account.js
template.order.js
```
Those file names are used to create the blocks inside of `script-tags.liquid`. This used to be ok before because if you were …
=> Support customers level template bundles

packages/slate-tools/cli/commands/start.js, packages/slate-tools/tools/dev-server/index.js
Partially fix #761.
Since we're serving from https, the domain needed to be `https` and not `http`.
I suggest we remove the local `ui` link for now until we have a solid solution. The `ui-external` works fine anyways.
- Run yarn watch
- Visit the external ui URL
- See this :
=> Fix browser sync ui-external

.github/probots.yml
Reverts Shopify/slate#817 
We discovered a bug with the GitHub checks API and working on a fix. Let’s disable it in the meantime.
=> Revert "Enable CLA bot"

packages/slate-env/__tests__/index.test.js, packages/slate-env/index.js
Fix #772 by surfacing an error that explicitly points out that store URLs should not include a trailing slash.
=> Prevent trailing slashes at the end of store URLs

packages/slate-cssvar-loader/index.js
This PR adds a check for an optional `-` hyphen character when using the `{%- style -%}...{%- endstyle -%}` Liquid tags to remove whitespace.
=> Add check for hyphens in Liquid style tag for CSS custom properties

packages/slate-tools/tools/asset-server/index.js, packages/slate-tools/tools/webpack/config/parts/core.js
Fixes https://github.com/Shopify/slate/issues/864, followup #877 
Had another look at this and found the source of the problem.. `liquidStyle` files are not being uploaded to Shopify servers because of some bad filtering on my end. Refining that filtering to exclude liquid styles will make sure its uploaded and you don't get a `MIME type` error.
Also can see the original `scss.liquid` file gets output into `dist` which might cause problems if uploaded to Shopify.
=> Fix liquid styles not uploading to Shopify

packages/slate-tools/cli/commands/start.js, packages/slate-tools/cli/index.js
Fixes #920, fixes #921 
Adds back a trigger for the `'slate-tools:start:start'` event and makes sure we're actually passing user config data to `'slate-tools:cli:start'`.
=> Fix cli:start and start:start analytics events

packages/slate-analytics/prompt.js
=> Update analytics to refer to beta instead of alpha

docs/v1/versioned_docs/version-1.0.0-beta.14/connect-to-your-store.md, packages/slate-env/__tests__/index.test.js, packages/slate-env/index.js, packages/slate-env/slate-env.schema.js, packages/slate-sync/index.js
This PR  expose the request timeout optional setting of themekit in the .env of slate.
A `.env` at the root such as:
```
SLATE_STORE=***.myshopify.com
SLATE_PASSWORD=***
SLATE_THEME_ID=***
SLATE_IGNORE_FILES=config/settings_data.json
SLATE_TIMEOUT=2m
```
will set the `timeout`  in `config.yml` at `2m` `SLATE_TIMEOUT` used by themekit.
This closes #831, fixes #699 and maybe some others I didn't saw.
- No major update
This is my first PR on Slate and maybe I'm not aware of everything in the project. I needed to modify the timeout for my own and saw some issues on this.
=> Expose request timeout of themekit in .env

packages/slate-tools/package.json
The point of PR #899 was to update the `slate-tools` package's dependencies to include `node-sass 4.10.0`, but, as @t-kelly pointed out, [`node-sass 4.11.0` is a stable release](https://www.npmjs.com/package/node-sass) and is probably more reliable.
[#778](https://github.com/Shopify/slate/issues/778)
=> Upgrade to node-sass@4.11.0

packages/slate-tools/package.json
Just trying to fix the error message in the console. I think it's a custom error message because it still pops up, but node-sass has been updated to version 4.10.0 inside the slate-tools package. Is this the only place where that dependency is found?
https://github.com/Shopify/slate/issues/778
=> Updating node-sass to version 4.10.0

packages/slate-tools/tools/dev-server/index.js
Fix #653, #796, #637, #420.
Shopify team just released a [parameter to hide the preview bar](https://github.com/Shopify/shopify/pull/184056) when previewing a theme.
Let's add the parameter to the URL by default to hide the bar and fixes the issues above.
=> Hide Shopify preview bar

packages/slate-sections-plugin/__tests__/index.test.js, packages/slate-sections-plugin/index.js
Fix a small issue introduced by https://github.com/Shopify/slate/pull/1000.
With the new Slate Sections Plugin introduction, the `sections` folder got removed from Webpack's context. I believe it was previously added there by the CopyWebpackPlugin.
This PR adds it back into the context so making changes to the files causes the browser to reload as it used to.
https://github.com/Shopify/slate/issues/1004
=> Add the sections folder back to webpack context

packages/slate-sections-plugin/index.js
The sections plugin was performing a lax check on the section filename against the genericTemplateName option, using the `includes()` method to see if the `relativePathFromSections` argument includes the `genericTemplateName` option value _anywhere_ within it.
This meant files such as `src/sections/collection-template.liquid` were compiled to `dist/sections/collection-template.liquid.liquid` and were not being updated on Shopify when changes were made locally with `yarn start` running.
This fix compares the basename of the `relativePathFromSections` argument instead.
=> Fix lax checking of filename against genericTemplateName in sections plugin

packages/slate-tools/tools/dev-server/index.js
Most other non-Slate 1.x development is via HTTP so by having HSTS on it really makes Shopify development tricky.
Most non-Shopify Slate 1.x development is done via HTTP. By leaving on Shopify's HSTS policy, it forces any localhost visits to happen via HTTPS. This simply removes that header from Shopify's proxied response so that HTTPS and HTTP can be used on localhost without issue.
https://github.com/Shopify/slate/issues/906
=> Disable HSTS for dev server

.github/ISSUE_TEMPLATE.md, .github/PULL_REQUEST_TEMPLATE.md, CONTRIBUTING.md, README.md, docs/v1/versioned_docs/version-1.0.0-beta.14/about.md
After re-evaluating Slate and its current state, Shopify has decided to officially end support for Slate.
With the launch of our new [section theme architecture](https://help.shopify.com/en/themes/development/sections-architecture) we're taking a step back to examine our current tooling and how we can deliver the best theming experience to our theme developers. 
Slate is not in line with our vision for themes moving forward and it does not solve two of the larger asks our theme developers have made:
* Local development of a Shopify theme
* Support for code versioning within themes
Slate was built upon [Theme Kit](https://github.com/Shopify/themekit) as an opinionated way to setup up a Shopify theme build. Shopify will continue to actively maintain and support the growth of Theme Kit …
=> End of support message
