package.json
Bump version of `slate-theme` to account for latest version of `slate-tools` and recent bug fixes.
=> bump slate-tools and slate-theme

docs/index.md
=> specifc -> specific

docs/_includes/sidebar.html, docs/js-examples/index.md, docs/theme-scaffold/index.md
Document recent addition of `cart.js` - related PR: https://github.com/Shopify/slate/pull/101
=> document cart.js

package.json
Bump version number to reflect:
* New `cart.js` helper
* Add `onReorder` events to `section.js`
* New `config.yml` file with `production` environment.
=> bump to version 0.10.0

README.md, package.json
I am just adding some small changes to the documentation, making the README easier to parse, and adding fields to the package.json. 
=> Small documentation edits

docs/theme-scaffold/index.md
Just browsing the docs and noticed a couple of missing links, should be fixed now.  
*Please provide a link to the associated GitHub issue.*  
No associated issue found.
=> Fixed a couple of broken links in docs.

src/scripts/sections/product.js, src/scripts/slate/variants.js
=> Remove unused variable

docs/commands/index.md
https://github.com/Shopify/slate-cli/issues/123
Adds docs for the new yarn option here: https://github.com/Shopify/slate-cli/pull/124
- N/A I have bumped the `package.json` version in a separate PR, if applicable.
=> Update docs with yarn option

config-sample.yml
Helps with #174. Adds a commented `settings_data.json` to `config.yml` to make it easy to avoid overwriting your current theme data.
=> Help users avoid resetting their theme data

package-lock.json, package.json
Update the starter theme to use slate-tools v0.3.3
=> Use @shopify/slate-tools v0.3.3

docs/theme-scaffold/index.md, src/locales/da.json
I'm currently creating a store in Danish, and though I'd add my local translation.
=> Adding danish translation

packages/slate-tools/src/tasks/deploy-sync.js, packages/slate-tools/src/tasks/includes/dev-script.js
Fixes https://github.com/Shopify/slate/issues/141
Copy of https://github.com/Shopify/slate-tools/pull/75. Changes were not merged successfully into `slate-tools` master before combining all repos in `shopify/slate`.
=> Persist theme preview bar minimize

packages/slate-theme/src/scripts/sections/product.js
Followup to #264. We missed one additional typo.
=> Fix a variable declaration typo in product.js

packages/slate-theme/src/templates/search.liquid
=> Fix search result item image liquid reference

docs/theme-scaffold/index.md, packages/slate-theme/src/locales/nl.json
Add dutch translation. (Double checked for spelling errors & correct context.)
:white_check_mark: I have updated the docs
=> Add dutch locale

packages/slate-theme/src/templates/gift_card.liquid
Auto-select the gift card's code when clicking on it. In other words, fix issue #279.
=> Auto-select the gift card's code on click

packages/slate-theme/src/scripts/slate/variants.js
Just a couple of changes to function comments.
=> Correct some function comments

packages/slate-theme/src/locales/en.default.json
=> Translation - customer.order.shipping_company updated to carrier

packages/slate-theme/src/locales/pt-BR.json
The previous copy contained some Spanish and terminology wasn't accurate. 
=> Update slate-theme with reviewed copy for PT-br

packages/slate-theme/src/locales/pt-PT.json
Previous content contained some Spanish and was not consistent.
=> Update slate-theme with PT-pt

packages/slate-tools/config/paths.js, packages/slate-tools/config/webpack.base.conf.js, packages/slate-tools/config/webpack.dev.conf.js, packages/slate-tools/config/webpack.prod.conf.js
Inject assets in all `layout/*.liquid` files. 
=> Add support for multiple layout files

docs/_includes/sidebar.html
=> Remove email link from docs

docs/_includes/sidebar.html
VSCode autofix was doing something funky with Liquid in previous commit.
=> Fix broken email link

docs/theme-scaffold/index.md
Fix broken link at Slate documentaion.
=> Update broken link at theme-scaffold/index.md

packages/slate-tools/README.md
=> Add docs for --skipPrompts flag

packages/slate-tools/README.md
=> Fix typo at packages/slate-tools/README.md

packages/slate-tools/package.json
=> Adds concat-style-loader to slate-tools package.json

packages/slate-tools/tools/dev-server/ssl/index.js
=> Add path module to dev-server/ssl module

packages/slate-tools/cli/prompts/skip-settings-data.js
This updates the text instructions for the `promptSettings` key found in the `slate.config.js` configuration file.
=> Update prompt settings instructions

packages/concat-style-loader/concat.js, packages/concat-style-loader/index.js
Fixes #491 
This makes sure that if you change one of these dependencies, it triggers watch to recompile.
=> Add @import file as dependencies in concat-css-loader

packages/slate-liquid-asset-loader/index.js, packages/slate-tools/cli/commands/start.js, packages/slate-tools/tools/webpack/config/core.js, packages/slate-tools/tools/webpack/config/dev.js, packages/slate-tools/tools/webpack/config/prod.js
Fixes https://github.com/Shopify/slate/issues/460
=> Fix asset url generated in slate-tools start

packages/slate-tools/cli/prompts/skip-settings-data.js
=> Make instructions for prompt settings more obvious

packages/slate-analytics/index.js, yarn.lock
Circle CI is currently breaking now that Node 10 has been released. This updates any broken dependencies.
=> Fix CircleCI running with Node 10

packages/slate-env/README.md, packages/slate-env/index.js, packages/slate-env/slate-env.config.js
Fix 'separated' typo in 3 places
=> Fix 'separated' typo

packages/slate-theme/src/templates/page.contact.liquid
Fixes https://github.com/Shopify/slate/issues/343
=> Remove extra whitespace from form element

packages/slate-cli/README.md, packages/slate-cli/src/commands/migrate.js
Fixes https://github.com/Shopify/slate/issues/504
=> Update config-sample.yml URL to 0.x branch

.travis.yml, package.json, packages/slate-analytics/index.js
We're deprecating CircleCI and moving towards Travis CI. This adds support for this new CI system.
=> Add Travis CI

packages/slate-cssvar-loader/index.js
Reverts Shopify/slate#532
@truribe your previous PR broke some of our tests. Could you reopen it and double check the tests that fail?
=> Revert "Modified slate-cssvar-loader to allow CSS variables without Liquid variables"

packages/slate-sync/index.js, packages/slate-tools/cli/commands/start.js, packages/slate-tools/cli/prompts/continue-if-published-theme.js
Fixes #428 
We were not catching any request errors when checking if we were deploying to the store's published theme. This PR makes sure we are handling any errors emitted from this action.
=> Throw an error if we fail to access Theme API

packages/slate-tag-webpack-plugin/index.js
Fixes https://github.com/Shopify/slate/issues/657.
=> Only set theme_packaged_with if the first settings panel is theme_info

packages/slate-env/README.md, packages/slate-env/slate-env.config.js
=> Fix typo in .env config comment

packages/slate-tools/tools/theme-lint/__tests__/index.test.js, packages/slate-tools/tools/webpack/config/__tests__/dev.test.js, packages/slate-tools/tools/webpack/config/__tests__/prod.test.js, packages/slate-tools/tools/webpack/config/dev.js, packages/slate-tools/tools/webpack/config/parts/__tests__/entry.test.js, packages/slate-tools/tools/webpack/config/parts/core.js, packages/slate-tools/tools/webpack/config/parts/entry.js, packages/slate-tools/tools/webpack/config/prod.js, packages/slate-tools/tools/webpack/config/utilities/get-layout-entrypoints.js, packages/slate-tools/tools/webpack/config/utilities/get-template-entrypoints.js
Followup to #742 
Reword test that checks if 'themelint.bin' config is passed to the appropriate method.
=> Themelint config test

packages/slate-config/__tests__/fixtures/slateWithError.config.js, packages/slate-config/__tests__/index.test.js, packages/slate-config/index.js
Fixes #748 
- Add tests to cover this scenario
=> Throw any errors that occur in slate.config.js

packages/slate-tools/slate-tools.schema.js
=> Add reduceIdents: false to default cssnano settings

.eslintrc, packages/slate-analytics/__tests__/index.test.js, packages/slate-analytics/index.js, packages/slate-analytics/prompt.js, packages/slate-env/__tests__/index.test.js, packages/slate-env/index.js, packages/slate-tools/cli/commands/start.js
Remove a ton of `eslint-disable` comments
=> Turn off no-process-env eslint rule

packages/slate-tools/cli/prompts/skip-settings-data.js
=> Remove extra } character in settings-data prompt

packages/slate-env/README.md
Followup to #702 
cc @huguestennier can we make sure any other docs we have on this are updated too?
=> Clarify how the the SLATE_IGNORE_FILES env variable works

README.md
Checking some CLA bits (sorry)
=> Fix License link

packages/slate-tools/tools/eslint/__tests__/index.test.js, packages/slate-tools/tools/eslint/index.js
=> Fix typo in eslint spawn command

css-examples/index.md
Added some more info about what push classes are and how they function, for improved clarity and to mitigate confusion with similarly named classes in [UIKit v2](https://getuikit.com/v2/docs/grid.html#source-ordering). Also mentioned that to include multiple breakpoints for push classes they can be separated with a comma in `$breakpoint-has-push` .
no existing issue exists
=> Added more descriptive info about push classes

packages/slate-tools/tools/webpack/script-tags.html, packages/slate-tools/tools/webpack/style-tags.html
Resolves #966 
Added extra check for Windows Slashes in the script and style tags snippet template.
=> Resolve Windows Slashes for styles and script tags snippets.

.github/ISSUE_TEMPLATE.md, .github/PULL_REQUEST_TEMPLATE.md, CONTRIBUTING.md, README.md
Update README and git templates
=> Update Slate project status - Low maintenance

packages/slate-tools/package.json, packages/slate-tools/tools/webpack/config/parts/core.js, packages/slate-tools/tools/webpack/config/utilities/inject-locales-into-settings-schema.js
Follow-up to #1013 (because I messed up the merge :')).
=> Add locales transformer for settings schema

packages/slate-tools/tools/dev-server/index.js
Fix head closing tag.
https://github.com/Shopify/slate/issues/1055
=> Fix head closing tag

docs/v1/versioned_docs/version-1.0.0-beta.14/Create-a-self-signed-SSL-certificate.md
=> Add linux command for local IP retrieve
